<Test> :
    GridLayout :
        cols : 1
        BoxLayout :
            MDLabel :
                text : 'Test'
                halign : 'center'
                font_size : 70
                id : test
                    
        BoxLayout :
            padding : 100
            MDRaisedButton :
                text : 'Run'
                size_hint : 1, .2
                pos_hint: {"center_x": .5, "center_y": .5}